=== scandurra/PAC/Tutorato4_XML_SAXLookup/src/corso.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT corso (nome, descrizione, sillabo, docenti, testi, erogazione, vincoli?, risorse?)>
<!ATTLIST corso
	uid ID #IMPLIED
	codice NMTOKEN #IMPLIED
	ssd CDATA #IMPLIED
>
<!ELEMENT rif-corso (#PCDATA)>
<!ATTLIST rif-corso
	rif NMTOKEN #IMPLIED
>
<!ELEMENT erogazione (crediti+, periodo, cdl, anno)>
<!ELEMENT mutuazioni (rif-corso+)>
<!ELEMENT propedeuticita (rif-corso+)>
<!ELEMENT risorse ((link | email)+)>
<!ELEMENT sillabo (argomento+)>
<!ELEMENT testi (testo+)>
<!ELEMENT testo (autore+, titolo, editore)>
<!ELEMENT vincoli (propedeuticita?, mutuazioni?)>
<!ELEMENT descrizione (obiettivi, prerequisiti?, esame)>
<!ELEMENT docenti (docente+)>
<!ELEMENT docente (nome, cognome)>
<!ATTLIST docente
	rif NMTOKEN #REQUIRED
>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT argomento (#PCDATA)>
<!ELEMENT autore (#PCDATA)>
<!ELEMENT cdl (#PCDATA)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT obiettivi (#PCDATA)>
<!ELEMENT periodo (#PCDATA)>
<!ELEMENT prerequisiti (#PCDATA)>
<!ELEMENT esame (#PCDATA)>
<!ELEMENT titolo (#PCDATA)>
<!ELEMENT editore (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email
	descrizione CDATA #REQUIRED
>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
	tipo (homepage | esercizi) #IMPLIED
	descrizione CDATA #IMPLIED
>
<!ELEMENT crediti EMPTY>
<!ATTLIST crediti
	tipologia (A | B | C | D | E | F) #REQUIRED
	numero NMTOKEN #REQUIRED
>

=== scandurra/PAC/Tutorato4_XML_SAXLookup/corso.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE corso SYSTEM "./corso.dtd">
<corso uid="0001" codice="F2I011" ssd="INGINF/05">
	<nome>Informatica III</nome>
	<descrizione>
		<obiettivi>Sviluppo di un'applicazione software con tecnologia Java/Eclipse</obiettivi>
		<prerequisiti>bla,bla</prerequisiti>
		<esame>bla,bla</esame>
	</descrizione>
	<sillabo>
		<argomento>Java GUI</argomento>
		<argomento>Design patterns</argomento>
		<argomento>Eclipse plug-in</argomento>
	</sillabo>
	<docenti>
		<docente rif="6235">
			<nome>Patrizia</nome>
			<cognome>Scandurra</cognome>
		</docente>
		<docente rif="6236">
			<nome>Angelo</nome>
			<cognome>Gargantini</cognome></docente>
	</docenti>
	<testi>
		<testo>
			<autore>Vito</autore>
			<autore>Frailis</autore>
			<autore>Gugliotta</autore>
			<autore>Omero</autore>
			<titolo>Introduzione alle Tecnologie del Web</titolo>
			<editore>McGraw-Hill</editore>
		</testo>
		<testo tipo="consigliato">
			<autore>Goodman</autore>
			<titolo>JavaScript &amp; DHTML Cookbook</titolo>
			<editore>O'Reilly</editore>
		</testo>
	</testi>
	<erogazione>
		<crediti tipologia="B" numero="6"/>
		<periodo>2</periodo>
		<cdl>Informatica Specialistica</cdl>
		<anno>1</anno>
	</erogazione>
	<vincoli>
		<propedeuticita>
			<corso rif="00002">Informatica III</corso>
		</propedeuticita>
		<mutuazioni>
			<corso rif="00003">Sistemi Informatici Distribuiti</corso>
		</mutuazioni>
	</vincoli>
	<risorse>
		<link tipo="esercizi">http://pagina</link>
		<link descrizione="altra pagina">http://pagina</link>
		<email descrizione="per domande al docente">scandurra@unibg.it</email>
	</risorse>
</corso>
